Creating RDDs By using parallelize( ) fucntion (learning spark 5.3)

In [0]:
'''
from pyspark.sql import SparkSession
spark = SparkSession\
.builder\
.appName("Python Spark create RDD example")\
.config("spark.some.config.option", "some-value")\
.getOrCreate()
'''
df = spark.sparkContext.parallelize([(1, 2, 3, 'a b c'),
                                     (4, 5, 6, 'd e f'),
                                     (7, 8, 9, 'g h i')]
                                   ).toDF(['col1', 'col2', 'col3', 'col4'])
df.show()

+----+----+----+-----+
|col1|col2|col3| col4|
+----+----+----+-----+
|   1|   2|   3|a b c|
|   4|   5|   6|d e f|
|   7|   8|   9|g h i|
+----+----+----+-----+

In [0]:
myData = spark.sparkContext.parallelize([(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)])
myData.collect()

Out[2]: [(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)]

By using createDataFrame( ) function

In [0]:
Employee = spark.createDataFrame([
('1', 'Joe', '70000', '1'),
('2', 'Henry', '80000', '2'),
('3', 'Sam', '60000', '2'),
('4', 'Max', '90000', '1')],
['Id', 'Name', 'Sallary','DepartmentId']
)

Employee.show()

+---+-----+-------+------------+
| Id| Name|Sallary|DepartmentId|
+---+-----+-------+------------+
|  1|  Joe|  70000|           1|
|  2|Henry|  80000|           2|
|  3|  Sam|  60000|           2|
|  4|  Max|  90000|           1|
+---+-----+-------+------------+

By using read and load functions

In [0]:
df = spark.read.format('com.databricks.spark.csv').options(header='true', inferschema='true').load("dbfs:/FileStore/tables/Advertising.csv", header=True)
# 위의 패스를 변경하여 실행해야 함. 
df.show(5)
df.printSchema()

+-----+-----+---------+-----+
|   TV|Radio|Newspaper|Sales|
+-----+-----+---------+-----+
|230.1| 37.8|     69.2| 22.1|
| 44.5| 39.3|     45.1| 10.4|
| 17.2| 45.9|     69.3|  9.3|
|151.5| 41.3|     58.5| 18.5|
|180.8| 10.8|     58.4| 12.9|
+-----+-----+---------+-----+
only showing top 5 rows

root
 |-- TV: double (nullable = true)
 |-- Radio: double (nullable = true)
 |-- Newspaper: double (nullable = true)
 |-- Sales: double (nullable = true)

In [0]:
df.withColumn('Sales2', df.Sales*1.1).show()

+-----+-----+---------+-----+------------------+
|   TV|Radio|Newspaper|Sales|            Sales2|
+-----+-----+---------+-----+------------------+
|230.1| 37.8|     69.2| 22.1|24.310000000000002|
| 44.5| 39.3|     45.1| 10.4|11.440000000000001|
| 17.2| 45.9|     69.3|  9.3|10.230000000000002|
|151.5| 41.3|     58.5| 18.5|             20.35|
|180.8| 10.8|     58.4| 12.9|14.190000000000001|
|  8.7| 48.9|     75.0|  7.2| 7.920000000000001|
| 57.5| 32.8|     23.5| 11.8|12.980000000000002|
|120.2| 19.6|     11.6| 13.2|             14.52|
|  8.6|  2.1|      1.0|  4.8|              5.28|
|199.8|  2.6|     21.2| 10.6|             11.66|
| 66.1|  5.8|     24.2|  8.6|              9.46|
|214.7| 24.0|      4.0| 17.4|             19.14|
| 23.8| 35.1|     65.9|  9.2|             10.12|
| 97.5|  7.6|      7.2|  9.7|             10.67|
|204.1| 32.9|     46.0| 19.0|20.900000000000002|
|195.4| 47.7|     52.9| 22.4|             24.64|
| 67.8| 36.6|    114.0| 12.5|13.750000000000002|
|281.4| 39.6|     55.8| 24.4|             26.84|
| 69.2| 20.5|     18.3| 11.3|12.430000000000001|
|147.3| 23.9|     19.1| 14.6|16.060000000000002|
+-----+-----+---------+-----+------------------+
only showing top 20 rows

Spark Operations = Transformations and Actions    
Transformations : construct a new RDD from a previous one. (Filtering)     
Actions : compute a result based on an RDD.

In [0]:
RDD.DataFrame vs PD.DataFrame (learning spark 5.3)

In [0]:
import pandas as pd
import numpy as np

list to dataframe

In [0]:
my_list = [['a', 1, 2], ['b', 2, 3],['c', 3, 4]]
col_name = ['A', 'B', 'C']

In [0]:
# caution for the columns= / 안하면 기본값인 행의 이름으로 설정됨
df=pd.DataFrame(my_list, columns=col_name)
print(df)

#
spark.createDataFrame(my_list, col_name).show()

   A  B  C
0  a  1  2
1  b  2  3
2  c  3  4
+---+---+---+
|  A|  B|  C|
+---+---+---+
|  a|  1|  2|
|  b|  2|  3|
|  c|  3|  4|
+---+---+---+

dictionary to dataframe

In [0]:
d = {'A': [0, 1, 0],
     'B': [1, 0, 1],
     'C': [1, 0, 0]}

In [0]:
df=pd.DataFrame(d)
print(df)
# Tedious for PySpark
spark.createDataFrame(np.array(list(d.values())).T.tolist(), list(d.keys())).show() 
# numpy.T : 전치행렬 변환

   A  B  C
0  0  1  1
1  1  0  0
2  0  1  0
+---+---+---+
|  A|  B|  C|
+---+---+---+
|  0|  1|  1|
|  1|  0|  0|
|  0|  1|  0|
+---+---+---+

csv to dataframe

In [0]:
# pd.DataFrame dp: DataFrame pandas
#dp = pd.read_csv('/dbfs/FileStore/tables/Advertising.csv') # databricks 에서는 제대로 작동안하는 거 같음 spark로 읽은 후에 Pandas로 변환하는 것으로...
#rdd.DataFrame. dp: DataFrame spark
ds = spark.read.csv(path='dbfs:/FileStore/tables/Advertising.csv',
#                sep=',',
#                encoding='UTF-8',
#                comment=None,
               header=True,
               inferSchema=True)
ds.show()

dp=ds.toPandas()
print(dp)

+-----+-----+---------+-----+
|   TV|Radio|Newspaper|Sales|
+-----+-----+---------+-----+
|230.1| 37.8|     69.2| 22.1|
| 44.5| 39.3|     45.1| 10.4|
| 17.2| 45.9|     69.3|  9.3|
|151.5| 41.3|     58.5| 18.5|
|180.8| 10.8|     58.4| 12.9|
|  8.7| 48.9|     75.0|  7.2|
| 57.5| 32.8|     23.5| 11.8|
|120.2| 19.6|     11.6| 13.2|
|  8.6|  2.1|      1.0|  4.8|
|199.8|  2.6|     21.2| 10.6|
| 66.1|  5.8|     24.2|  8.6|
|214.7| 24.0|      4.0| 17.4|
| 23.8| 35.1|     65.9|  9.2|
| 97.5|  7.6|      7.2|  9.7|
|204.1| 32.9|     46.0| 19.0|
|195.4| 47.7|     52.9| 22.4|
| 67.8| 36.6|    114.0| 12.5|
|281.4| 39.6|     55.8| 24.4|
| 69.2| 20.5|     18.3| 11.3|
|147.3| 23.9|     19.1| 14.6|
+-----+-----+---------+-----+
only showing top 20 rows

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

Pandas DataFrame

In [0]:
# Pandas dataframe
dp.head(4)

Out[65]: Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [0]:
dp.columns # columns

Out[67]: TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [0]:
dp.dtypes # data types

Out[69]: TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

Spark DataFrame

In [0]:
# Spark dataframe
ds.show(4)
ds.columns

+-----+-----+---------+-----+
|   TV|Radio|Newspaper|Sales|
+-----+-----+---------+-----+
|230.1| 37.8|     69.2| 22.1|
| 44.5| 39.3|     45.1| 10.4|
| 17.2| 45.9|     69.3|  9.3|
|151.5| 41.3|     58.5| 18.5|
+-----+-----+---------+-----+
only showing top 4 rows

Out[72]: ['TV', 'Radio', 'Newspaper', 'Sales']

In [0]:
ds.dtypes # data types

Out[71]: [('TV', 'double'),
 ('Radio', 'double'),
 ('Newspaper', 'double'),
 ('Sales', 'double')]

fill Null values

In [0]:
my_list = [['male', 1, None],
           ['female', 2, 3],
           ['male', 3, 4]]
dp = pd.DataFrame(my_list, columns=['A', 'B', 'C'])
ds = spark.createDataFrame(my_list, ['A', 'B', 'C'])

#
print(dp)
ds.show()

        A  B    C
0    male  1  NaN
1  female  2  3.0
2    male  3  4.0
+------+---+----+
|     A|  B|   C|
+------+---+----+
|  male|  1|null|
|female|  2|   3|
|  male|  3|   4|
+------+---+----+

In [0]:
print(dp.fillna(-99))
#
ds.fillna(-99).show()

        A  B     C
0    male  1 -99.0
1  female  2   3.0
2    male  3   4.0
+------+---+---+
|     A|  B|  C|
+------+---+---+
|  male|  1|-99|
|female|  2|  3|
|  male|  3|  4|
+------+---+---+

replace the values

In [0]:
# caution: you need to chose specific col
dp.A.replace(['male', 'female'],[1, 0], inplace=True)
print(dp)
#caution: Mixed type replacements are not supported
ds.na.replace(['male','female'],['1','0']).show()

   A  B    C
0  1  1  NaN
1  0  2  3.0
2  1  3  4.0
+---+---+----+
|  A|  B|   C|
+---+---+----+
|  1|  1|null|
|  0|  2|   3|
|  1|  3|   4|
+---+---+----+

Rename columns

In [0]:
my_list = [[230.1, 37.8, 69.2, 22.1],
          [44.5, 39.3, 45.1, 10.4],
          [17.2, 45.9, 69.3, 9.3],
          [151.5, 41.3, 58.5, 18.5]]
dp = pd.DataFrame(my_list)
print(dp)

       0     1     2     3
0  230.1  37.8  69.2  22.1
1   44.5  39.3  45.1  10.4
2   17.2  45.9  69.3   9.3
3  151.5  41.3  58.5  18.5
+-----+----+----+----+
|   _1|  _2|  _3|  _4|
+-----+----+----+----+
|230.1|37.8|69.2|22.1|
| 44.5|39.3|45.1|10.4|
| 17.2|45.9|69.3| 9.3|
|151.5|41.3|58.5|18.5|
+-----+----+----+----+

In [0]:
dp.columns = ['a','b','c','d']
dp.head(4)

,a,b,c,d
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5